AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'

#
# Layout
#

Metrics/LineLength:
  Max: 128

#
# Metrics
#

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 128
  ExcludedMethods: [ 'describe' ]

Metrics/ClassLength:
  Max: 128

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

#
# Naming
#

Naming/UncommunicativeMethodParamName:
  Enabled: false

#
# Style
#

Style/AccessModifierDeclarations:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
