# encoding: binary
require 'rbnacl/secret_box/xsalsa20_poly1305'
module Crypto
  # The SecretBox class boxes and unboxes messages
  #
  # This class uses the given secret key to encrypt and decrypt messages.
  #
  # It is VITALLY important that the nonce is a nonce, i.e. it is a number used
  # only once for any given pair of keys.  If you fail to do this, you
  # compromise the privacy of the messages encrypted. Give your nonces a
  # different prefix, or have one side use an odd counter and one an even counter.
  # Just make sure they are different.
  #
  # The ciphertexts generated by this class include a 16-byte authenticator which
  # is checked as part of the decryption.  An invalid authenticator will cause
  # the unbox function to raise.  The authenticator is not a signature.  Once
  # you've looked in the box, you've demonstrated the ability to create
  # arbitrary valid messages, so messages you send are repudiatable.  For
  # non-repudiatable messages, sign them before or after encryption.
  class SecretBox
    # The default primitive to use
    DEFAULT_PRIMITIVE = SecretBox::XSalsa20Poly1305

    # Create a new SecretBox
    #
    # Sets up the Box with a secret key fro encrypting and decrypting messages.
    #
    # @param key [String] The key to encrypt and decrypt with
    # @param encoding [Symbol] Parse key from the given encoding
    #
    # @raise [Crypto::LengthError] on invalid keys
    #
    # @return [Crypto::SecretBox] The new Box, ready to use
    def initialize(key, encoding = :raw, primitive = DEFAULT_PRIMITIVE)
      @key = Encoder[encoding].decode(key) if key
      @primitive = primitive.new(@key)
    end

    # returns the defaul primitive for the SecretBox class
    #
    # @return [Symbol] the default primitive
    def self.primitive
      DEFAULT_PRIMITIVE.primitive
    end

    # returns the primitive of this instance
    #
    # @return [Symbol] the default primitive
    def primitive
      @primitive.primitive
    end
    

    # Encrypts a message
    #
    # Encrypts the message with the given nonce to the key set up when
    # initializing the class.  Make sure the nonce is unique for any given
    # key, or you might as well just send plain text.
    #
    # This function takes care of the padding required by the NaCL C API.
    #
    # @param nonce [String] A 24-byte string containing the nonce.
    # @param message [String] The message to be encrypted.
    #
    # @raise [Crypto::LengthError] If the nonce is not valid
    #
    # @return [String] The ciphertext without the nonce prepended (BINARY encoded)
    def box(nonce, message)
      @primitive.box(nonce, message)
    end
    alias encrypt box

    # Decrypts a ciphertext
    #
    # Decrypts the ciphertext with the given nonce using the key setup when
    # initializing the class.
    #
    # This function takes care of the padding required by the NaCL C API.
    #
    # @param nonce [String] A 24-byte string containing the nonce.
    # @param ciphertext [String] The message to be decrypted.
    #
    # @raise [Crypto::LengthError] If the nonce is not valid
    # @raise [Crypto::CryptoError] If the ciphertext cannot be authenticated.
    #
    # @return [String] The decrypted message (BINARY encoded)
    def open(nonce, ciphertext)
      @primitive.open(nonce, ciphertext)
    end
    alias decrypt open
  end
end
